### ISSUE TITLE
Desura not starting in ubuntu 12.04 due to GLIBCXX_3.4.19 not found

### ISSUE THREAD

**Issue by acafresna** [desura/desura-app#1003]
Ubuntu 12.04 64 bits updated. When trying the latest version from http://www.desura.com/desura-x86_64.tar.gz it installs but throws the following error when trying to start it:

    ff@jos:~/juegos/desura$ ./desura 
    /home/ff/juegos/desura/lib/desura: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /home/ff/juegos/desura/lib/desura)
    ff@jos:~/juegos/desura$ 

and nothing else happens.

**Comment by codethulu** [comment]
We are currently building this project against gcc 4.8 on ubuntu 14.04. You can resolve this issue by installing later c/c++ libraries (eg, by adding a ppa and installing gcc 4.8) or by upgrading to ubuntu 14.04.

See also: http://askubuntu.com/questions/271388/how-to-install-gcc-4-8

**Comment by acafresna** [comment]
Thanks a lot! It really helped and desura works again in my system. As documentation in case someone else with the same problem comes over here, I will add that after adding the repository toolchain PPA of the link above, and installing gcc4.9, it is still necesary to run the following command to get the right libraries:

    sudo apt-get install libstdc++6=4.9.2-0ubuntu1~12.04

And that's all!

**Comment by xros** [comment]
on ubuntu12.04, if you want to install gcc according to the PPA above, YOUR SYSTEM WILL CRASH...
Many packages will be removed because of the indendency of gcc 4.9 , especially the crash about losing dependency of package 'ia32-libs'. That http://askubuntu.com/questions/271388/how-to-install-gcc-4-8 can help you have fun with gcc 4.8, 4.9, or 5 but your stable LTS ubuntu will not be stable anymore. For the game,yes, you can play.
