### ISSUE TITLE
Another error stopping Desura launching, looking in the wrong place for libs?

### ISSUE THREAD

**Issue by liamdawe** [desura/desura-app#994]
This is another error from using the latest 64bit client download:

liam@liam-desktop ~ $ '/home/liam/Downloads/desura/desura' 
/devroot/teamcity/buildAgent/work/2d0cde112ff3bd73/src/include/SharedObjectLoader.h:83 - Error loading library libuicore.so: 'libjpeg.so.62: cannot open shared object file: No such file or directory' [LD_LIBRARY_PATH=/home/liam/Downloads/desura/lib/lib/lib/]
$XDG_CONFIG_HOME not set, falling back to $HOME/.config.$XDG_CACHE_HOME not set, falling back to $HOME/.cache.

Looks like you're setting it to look on your build system, and not the local directory on my system?

It also looks like it installs the /lib folder three times? The first 2 /lib folders seem to have all the Desura files, and the third /lib/lib/lib folder seems to just have the libs.

**Comment by Tokiolabs** [comment]
Do'h... Someone is getting smacked for this one!  It's 6:00am here -- Good time to call and wake up some developers!

**Comment by codethulu** [comment]
There are three issues in this ticket.

The first should be resolved in 320.31/120.26.

The second is a misunderstanding of process. That is the location of the relevant error in the source according to the compiled binary; you can symlink or otherwise re-direct the source to that location for debugging. It was unable to find that library either in the local directory or the system libs directory.

The third has been split into a separate issue. #996
